bbxdeveloper/bbxBE

bbxBE.Application/BLL/bllOrigin.cs
bbxBE.Application/Commands/cmdCustomer/createCustomerCommand.cs
bbxBE.Application/Commands/cmdOrigin/createOriginCommand.cs
bbxBE.Application/Commands/cmdOrigin/createOriginCommandValidator.cs
bbxBE.Application/Commands/cmdOrigin/deleteOriginCommand.cs
bbxBE.Application/Commands/cmdOrigin/deleteOriginCommandValidator.cs
bbxBE.Application/Commands/cmdOrigin/updateOriginCommand.cs
bbxBE.Application/Commands/cmdOrigin/updateOriginCommandValidator.cs
bbxBE.Application/Interfaces/Repositories/IOriginRepositoryAsync.cs
bbxBE.Application/Mappings/MapCommands.cs
bbxBE.Application/Mappings/MapQueries.cs
bbxBE.Application/Queries/QueryServiceRegistration.cs
bbxBE.Application/Queries/ViewModels/GetOriginViewModel.cs
bbxBE.Application/Queries/qOrigin/GetOriginHandler.cs
bbxBE.Application/Queries/qOrigin/QueryOriginHandler.cs
bbxBE.Domain/Entities/Origin.cs
bbxBE.Infrastructure.Persistence/Contexts/ApplicationDbContext.cs
bbxBE.Infrastructure.Persistence/Repositories/OriginRepositoryAsync.cs
bbxBE.Infrastructure.Persistence/ServiceRegistration.cs
bbxBE.WebApi/Controllers/v1/OriginController.cs
bbxBE.WebApi/bbxBE.WebApi.xml

Origin CRUD

---

bbxBE.Application/Reports/Offer.trdx

Offer report version 1.0 created

Offer report version 1.0 added

---

bbxBE.Application/Reports/Offer.trdx

Offer report version 1.0 created

Offer repirt fix: how to handle discrount values

---

bbxBE.Application/Reports/Offer.trdx

offerLines detail fixed

---

bbxBE.Application/Commands/cmdEmail/sendEmailCommand.cs
bbxBE.Application/Commands/cmdEmail/sendEmailCommandValidator.cs
bbxBE.Application/Consts/bbxBEConsts.cs
bbxBE.Application/bbxBE.Application.csproj
bbxBE.WebApi/Controllers/v1/InfrastructureController.cs
bbxBE.WebApi/bbxBE.WebApi.xml

EmailSend by SendGrid infra added

EmailSend by SendGrid infra added

---

bbxBE.Application/BLL/bllInvCtrl.cs
bbxBE.Application/BLL/bllInvCtrlPeriod.cs
bbxBE.Application/Commands/cmdInvCtrl/printInvCtrlCommand.cs
bbxBE.Application/Commands/cmdInvCtrl/printInvCtrlCommandValidator.cs
bbxBE.Application/Commands/cmdInvCtrlPeriod/printInvCtrlPeriodCommand.cs
bbxBE.Application/Commands/cmdInvCtrlPeriod/printInvCtrlPeriodCommandValidator.cs
bbxBE.Application/bbxBE.Application.csproj
bbxBE.WebApi/Controllers/v1/InvCtrlICPController.cs
bbxBE.WebApi/Controllers/v1/InvCtrlPeriodController.cs

InvCtrl and InvCtrlPeriod report endpoints added

InvCtrl and InvCtrlPeriod report endpoints added

---

bbxBE.Application/BLL/bllInvCtrl.cs
bbxBE.Application/BLL/bllInvCtrlPeriod.cs
bbxBE.Application/Commands/cmdInvCtrl/printInvCtrlCommand.cs
bbxBE.Application/Commands/cmdInvCtrl/printInvCtrlCommandValidator.cs
bbxBE.Application/Commands/cmdInvCtrlPeriod/printInvCtrlPeriodCommand.cs
bbxBE.Application/Commands/cmdInvCtrlPeriod/printInvCtrlPeriodCommandValidator.cs

InvCtrl Reports render endpoint input fixes

InvCtrl Reports render endpoint input fixes

---

bbxBE.Application/Reports/Invoice.trdx

Invoice margin bug fixing

---

bbxBE.Application/Commands/cmdImport/importProductCommand.cs

Product Import fixing

---

bbxBE.Application/Reports/InvoiceDNI.trdx
bbxBE.Application/Reports/InvoiceDNO.trdx
bbxBE.Application/Reports/InvoiceINC.trdx
bbxBE.Application/Reports/Offer.trdx

Update on InvoiceINC, InvoiceDNO, IncoiceDNI and Offer reports

Update on InvoiceINC, InvoiceDNO, IncoiceDNI and Offer reports

---

bbxBE.Application/Reports/Offer.trdx

Offer report fix

---

bbxBE.Application/Reports/Invoice.trdx

Invoice format problems fix

---

bbxBE.Application/Reports/InvCtrlICP.trdx
bbxBE.Application/Reports/Invoice.trdx
bbxBE.Application/Reports/InvoiceDNI.trdx
bbxBE.Application/Reports/InvoiceDNO.trdx
bbxBE.Application/Reports/InvoiceINC.trdx
bbxBE.Application/Reports/Invoice_1.trdx

https://trello.com/c/1Lig8p2X/367-0286-notice-nem-jelenik-nem-egy-sz%C3%A1mla-ill-sz%C3%A1ll-nyomtatv%C3%A1nyon

Számla, szállítólevél myomtatványok jav.

---

bbxBE.Application/Reports/Offer.trdx

- currency added
- address changed
- grid columns: removed

Offer report fix around: columns, currency

---

bbxBE.Application/Reports/AggregateINC.trdx
bbxBE.Application/Reports/AggregateINV.trdx
bbxBE.Application/Reports/InvCtrlICPReport.trdx
bbxBE.Application/Reports/Invoice.trdx
bbxBE.Application/Reports/InvoiceDNI.trdx
bbxBE.Application/Reports/InvoiceDNO.trdx
bbxBE.Application/Reports/InvoiceINC.trdx

aggregateINC, InvoiceINC, Invoice, InvoiceDNI, InvoiceDNO fixed:
- last summary
- column name: terméknév

#0477,#0476 - report fixes

---

bbxBE.Application/Reports/AggregateINC.trdx
bbxBE.Application/Reports/AggregateINV.trdx
bbxBE.Application/Reports/AggregateSubINC.trdx
bbxBE.Application/Reports/AggregateSubINV.trdx
bbxBE.Application/Reports/InvoiceINC.trdx

0476: Offer report and

---

bbxBE.Application/Reports/InvoiceJSB.trdx
bbxBE.Application/bbxBE.Application.csproj

0573 - InvoiceJSB.trdx added

---

bbxBE.Application/Reports/WarehouseTransfer.trdx
bbxBE.Application/bbxBE.Application.csproj

WarehouseTransfer report created
WarehouseTransfer report added to solution

WarehouseTransfer report added

---

bbxBE.Application/Reports/InvCtrlICP.trdx
bbxBE.Application/Reports/InvCtrlICPReport.trdx

IncCtrlICP date format in right bottom corner

IncCtrlICP date format in right bottom corner

---

bbxBE.Application/Reports/AggregateINC.trdx
bbxBE.Application/Reports/AggregateINV.trdx
bbxBE.Application/Reports/InvCtrlICP.trdx
bbxBE.Application/Reports/InvCtrlICPReport.trdx
bbxBE.Application/Reports/Offer.trdx

Summary Discount in Aggregates
Current date time in IncCtrls and Offer

Summary Discount in Aggregates

---

bbxBE.Application/Reports/WarehouseTransfer.trdx

- datum mezo
- megjegyzes mezo legyen HTML

Raktarkozi atadas report javitasa:

---

bbxBE.Application/Reports/AggregateINV.trdx
bbxBE.Application/Reports/Invoice.trdx
bbxBE.Application/Reports/InvoiceDNO.trdx
bbxBE.Application/Reports/InvoiceJSK.trdx

f/1197 - forditott afa klauza added

f/1193 - termekdij klauza added

---

bbxBE.Application/Commands/cmdInvoice/createInvoiceCommand.cs
bbxBE.Infrastructure.Persistence/Repositories/InvoiceRepositoryAsync.cs

newUnitPrice2 --> newUnitPrice2HUF

newUnitPrice1 --> newUnitPrice1HUF

---

bbxBE.WebApi/Controllers/v1/AuthController.cs

/api/v1/Auth/auth/v1/logout → /api/auth/v1/logout

/api/v1/Auth/auth/v1/login → /api/auth/v1/login

---

bbxBE.Application/Reports/AggregateINC.trdx
bbxBE.Application/Reports/AggregateINV.trdx
bbxBE.Application/Reports/Invoice.trdx
bbxBE.Application/Reports/InvoiceDNI.trdx
bbxBE.Application/Reports/InvoiceDNO.trdx
bbxBE.Application/Reports/InvoiceINC.trdx
bbxBE.Application/Reports/InvoiceJSB.trdx
bbxBE.Application/Reports/InvoiceJSK.trdx

add a solid line in the header blokk

add a solid line in the header blokk
